/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_api_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team Invitations */
        get: operations["team_invitations_api_teams__team_id__invitations_get"];
        put?: never;
        /** Invite Team Member */
        post: operations["invite_team_member_api_teams__team_id__invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_id}/invitations/{invitation_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Invitation */
        post: operations["revoke_invitation_api_teams__team_id__invitations__invitation_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect Invitation */
        get: operations["inspect_invitation_api_invitations__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Invitation */
        post: operations["activate_invitation_api_invitations__token__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/{token}/accept-existing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Existing Account Invitation */
        post: operations["activate_existing_account_invitation_api_invitations__token__accept_existing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/wecom/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wecom Status */
        get: operations["wecom_status_api_integrations_wecom_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/wecom/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Wecom Document */
        post: operations["create_wecom_document_api_integrations_wecom_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/wecom/documents/{docid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wecom Document */
        get: operations["get_wecom_document_api_integrations_wecom_documents__docid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Members */
        get: operations["list_project_members_api_projects__project_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/decompositions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decompose Project */
        post: operations["decompose_project_api_projects__project_id__decompositions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/task-overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Task Overview */
        get: operations["project_task_overview_api_projects__project_id__task_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Conversations */
        get: operations["list_project_conversations_api_projects__project_id__conversations_get"];
        put?: never;
        /** Create Project Conversation */
        post: operations["create_project_conversation_api_projects__project_id__conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Chat Messages */
        get: operations["list_project_chat_messages_api_project_conversations__conversation_id__messages_get"];
        put?: never;
        /** Send Project Chat Message */
        post: operations["send_project_chat_message_api_project_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Stage */
        post: operations["create_stage_api_projects__project_id__stages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stages/{stage_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Stage */
        patch: operations["update_stage_api_stages__stage_id__patch"];
        trace?: never;
    };
    "/api/tasks/{task_id}/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Task Action */
        post: operations["task_action_api_tasks__task_id__actions__action__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Submissions */
        get: operations["task_submissions_api_tasks__task_id__submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task History */
        get: operations["task_history_api_tasks__task_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/external-contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** External Contacts */
        get: operations["external_contacts_api_external_contacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/external-dependency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task External Dependency */
        get: operations["task_external_dependency_api_tasks__task_id__external_dependency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/external-reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** External Reminders */
        get: operations["external_reminders_api_external_reminders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate-extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Candidate Extraction */
        post: operations["create_candidate_extraction_api_candidate_extractions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Candidates */
        get: operations["list_candidates_api_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Candidate */
        patch: operations["update_candidate_api_candidates__candidate_id__patch"];
        trace?: never;
    };
    "/api/candidates/{candidate_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Candidate Route */
        post: operations["confirm_candidate_route_api_candidates__candidate_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/ignore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ignore Candidate */
        post: operations["ignore_candidate_api_candidates__candidate_id__ignore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/agent-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Agent Runs */
        get: operations["task_agent_runs_api_tasks__task_id__agent_runs_get"];
        put?: never;
        /** Create Agent Run */
        post: operations["create_agent_run_api_tasks__task_id__agent_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agent Runs */
        get: operations["list_agent_runs_api_agent_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contributions */
        get: operations["contributions_api_contributions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentRunRead */
        AgentRunRead: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** Status */
            status: string;
            /** Execution Mode */
            execution_mode: string | null;
            /** Degraded */
            degraded: boolean;
            /** Fallback Reason */
            fallback_reason: string | null;
            /** Prompt Version */
            prompt_version: string;
            /** Attempt Count */
            attempt_count: number;
            /** Max Attempts */
            max_attempts: number;
            /** Output Text */
            output_text: string;
            /** Error Message */
            error_message: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Task Title */
            task_title: string;
            /** Project Id */
            project_id: string;
            /** Project Name */
            project_name: string;
            /** Requested By Name */
            requested_by_name: string;
        };
        /** AgentRunStartRequest */
        AgentRunStartRequest: {
            /**
             * Revision Instruction
             * @default
             */
            revision_instruction: string;
        };
        /** AgentRunStartResponse */
        AgentRunStartResponse: {
            run: components["schemas"]["AgentRunRead"];
            /** Idempotent Replay */
            idempotent_replay: boolean;
        };
        /** CandidateConfirmRequest */
        CandidateConfirmRequest: {
            /** Expected Version */
            expected_version: number;
        };
        /** CandidateConfirmResponse */
        CandidateConfirmResponse: {
            candidate: components["schemas"]["CandidateRead"];
            task: components["schemas"]["TaskRead"];
            /**
             * Idempotent Replay
             * @default false
             */
            idempotent_replay: boolean;
        };
        /** CandidateExtractionRequest */
        CandidateExtractionRequest: {
            /** Project Id */
            project_id: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "MEETING" | "CHAT" | "DOCUMENT" | "AI_CHAT";
            /** Title */
            title: string;
            /** Content */
            content: string;
        };
        /** CandidateExtractionResponse */
        CandidateExtractionResponse: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Candidates */
            candidates: components["schemas"]["CandidateRead"][];
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "LIVE" | "MOCK" | "FALLBACK";
            /** Degraded */
            degraded: boolean;
            /** Fallback Reason */
            fallback_reason: string | null;
            /** Cached */
            cached: boolean;
            /** Call Id */
            call_id: string;
        };
        /** CandidateRead */
        CandidateRead: {
            /** Id */
            id: string;
            /** Source Snapshot Id */
            source_snapshot_id: string;
            /** Project Id */
            project_id: string;
            /** Stage Id */
            stage_id: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Deliverable */
            deliverable: string;
            /** Owner Id */
            owner_id: string | null;
            /** Reviewer Id */
            reviewer_id: string | null;
            execution_mode: components["schemas"]["ExecutionMode"];
            /** Due At */
            due_at: string | null;
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence: string;
            /** Status */
            status: string;
            /** Created Task Id */
            created_task_id: string | null;
            /** Version */
            version: number;
        };
        /** CandidateUpdateRequest */
        CandidateUpdateRequest: {
            /** Expected Version */
            expected_version: number;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Deliverable */
            deliverable?: string | null;
            /** Stage Id */
            stage_id?: string | null;
            /** Owner Id */
            owner_id?: string | null;
            /** Reviewer Id */
            reviewer_id?: string | null;
            execution_mode?: components["schemas"]["ExecutionMode"] | null;
            /** Due At */
            due_at?: string | null;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** ContributionRead */
        ContributionRead: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** User Id */
            user_id: string;
            /** User Name */
            user_name: string;
            /** Event Type */
            event_type: string;
            /** Submission Version */
            submission_version: number;
            /** Points */
            points: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ExecutionMode
         * @enum {string}
         */
        ExecutionMode: "HUMAN" | "AI" | "HYBRID";
        /** ExternalContactRead */
        ExternalContactRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Organization */
            organization: string;
            /** Channel */
            channel: string;
        };
        /** ExternalDependencyRead */
        ExternalDependencyRead: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** Contact Id */
            contact_id: string;
            /** Contact Name */
            contact_name: string;
            /** Item */
            item: string;
            /**
             * Expected At
             * Format: date-time
             */
            expected_at: string;
            /** Internal Followup User Id */
            internal_followup_user_id: string;
            /** Internal Followup User Name */
            internal_followup_user_name: string;
            /** Recovery Action */
            recovery_action: string;
            /** Last Followup At */
            last_followup_at: string | null;
            /** External Feedback Status */
            external_feedback_status: string;
            /** Actual Received At */
            actual_received_at: string | null;
            /** Reminder Sent */
            reminder_sent: boolean;
            /**
             * Reminder Level
             * @enum {string}
             */
            reminder_level: "NORMAL" | "UPCOMING" | "OVERDUE" | "RECEIVED";
        };
        /** ExternalReminderRead */
        ExternalReminderRead: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** Reminder Type */
            reminder_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvitationAcceptRequest */
        InvitationAcceptRequest: {
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
        /** InvitationAdminRead */
        InvitationAdminRead: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            role: components["schemas"]["TeamRole"];
            /** Project Id */
            project_id?: string | null;
            /** Project Name */
            project_name?: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "EXPIRED" | "ACCEPTED" | "REVOKED";
        };
        /** InvitationCreateRequest */
        InvitationCreateRequest: {
            /** Email */
            email: string;
            /** @default MEMBER */
            role: components["schemas"]["TeamRole"];
            /** Project Id */
            project_id?: string | null;
            project_role?: components["schemas"]["ProjectRole"] | null;
        };
        /** InvitationCreatedRead */
        InvitationCreatedRead: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Team Id */
            team_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Activation Token */
            activation_token: string;
            /**
             * Email Delivery
             * @enum {string}
             */
            email_delivery: "SENT" | "NOT_CONFIGURED" | "FAILED";
        };
        /** InvitationPublicRead */
        InvitationPublicRead: {
            /** Email */
            email: string;
            /** Team Name */
            team_name: string;
            /** Inviter Name */
            inviter_name: string;
            /** Account Exists */
            account_exists: boolean;
            role: components["schemas"]["TeamRole"];
            /** Project Name */
            project_name?: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** ProjectChatMessageRead */
        ProjectChatMessageRead: {
            /** Id */
            id: string;
            /** Conversation Id */
            conversation_id: string;
            /** Author Id */
            author_id: string | null;
            /** Author Name */
            author_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "USER" | "ASSISTANT";
            /** Content */
            content: string;
            /** Execution Mode */
            execution_mode: ("LIVE" | "MOCK" | "FALLBACK") | null;
            /** Prompt Version */
            prompt_version: string | null;
            /** Context Task Ids */
            context_task_ids: string[];
            /** Context Task Titles */
            context_task_titles: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProjectChatSendRequest */
        ProjectChatSendRequest: {
            /** Content */
            content: string;
        };
        /** ProjectChatSendResponse */
        ProjectChatSendResponse: {
            user_message: components["schemas"]["ProjectChatMessageRead"];
            assistant_message: components["schemas"]["ProjectChatMessageRead"];
        };
        /** ProjectConversationCreateRequest */
        ProjectConversationCreateRequest: {
            /**
             * Title
             * @default 新对话
             */
            title: string;
        };
        /** ProjectConversationRead */
        ProjectConversationRead: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Title */
            title: string;
            /** Created By */
            created_by: string;
            /** Created By Name */
            created_by_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Message Count */
            message_count: number;
        };
        /** ProjectCreateRequest */
        ProjectCreateRequest: {
            /** Team Id */
            team_id?: string | null;
            /** Name */
            name: string;
            /**
             * Client
             * @default 内部
             */
            client: string;
            /**
             * Objective
             * @default
             */
            objective: string;
            /** Owner Id */
            owner_id?: string | null;
            /**
             * Next Milestone
             * @default
             */
            next_milestone: string;
            /** Due At */
            due_at?: string | null;
        };
        /** ProjectDecompositionRequest */
        ProjectDecompositionRequest: {
            /**
             * Instruction
             * @default
             */
            instruction: string;
            /**
             * Max Candidates
             * @default 8
             */
            max_candidates: number;
        };
        /** ProjectMemberRead */
        ProjectMemberRead: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["ProjectRole"];
            /** Is Active */
            is_active: boolean;
        };
        /** ProjectMemberWorkloadRead */
        ProjectMemberWorkloadRead: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Task Count */
            task_count: number;
            /** Active Count */
            active_count: number;
            /** Attention Count */
            attention_count: number;
            /** Completed Count */
            completed_count: number;
        };
        /** ProjectRead */
        ProjectRead: {
            /** Id */
            id: string;
            /** Team Id */
            team_id: string;
            /** Name */
            name: string;
            /** Client */
            client: string;
            /** Objective */
            objective: string;
            /** Owner Id */
            owner_id: string;
            /** Owner Name */
            owner_name: string;
            /** Next Milestone */
            next_milestone: string;
            /** Due At */
            due_at: string | null;
            /** Progress */
            progress: number;
            /**
             * Health
             * @enum {string}
             */
            health: "正常" | "有风险" | "需关注";
            /** Health Reasons */
            health_reasons: string[];
            /** Current Stage */
            current_stage: string;
            /** Stages */
            stages: components["schemas"]["StageRead"][];
        };
        /**
         * ProjectRole
         * @enum {string}
         */
        ProjectRole: "OWNER" | "MEMBER" | "VIEWER";
        /** ProjectTaskOverviewRead */
        ProjectTaskOverviewRead: {
            /** Project Id */
            project_id: string;
            /** Progress */
            progress: number;
            /**
             * Health
             * @enum {string}
             */
            health: "正常" | "有风险" | "需关注";
            /** Task Count */
            task_count: number;
            /** Active Candidate Count */
            active_candidate_count: number;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Member Workloads */
            member_workloads: components["schemas"]["ProjectMemberWorkloadRead"][];
        };
        /** ProjectUpdateRequest */
        ProjectUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Client */
            client?: string | null;
            /** Objective */
            objective?: string | null;
            /** Owner Id */
            owner_id?: string | null;
            /** Next Milestone */
            next_milestone?: string | null;
            /** Due At */
            due_at?: string | null;
        };
        /** StageCreateRequest */
        StageCreateRequest: {
            /** Name */
            name: string;
            /** Owner Id */
            owner_id: string;
            /**
             * Weight
             * @default 1
             */
            weight: number;
        };
        /** StageRead */
        StageRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: number;
            status: components["schemas"]["StageStatus"];
            /** Progress */
            progress: number;
            /**
             * Health
             * @default 正常
             * @enum {string}
             */
            health: "正常" | "有风险" | "需关注";
        };
        /**
         * StageStatus
         * @enum {string}
         */
        StageStatus: "PLANNED" | "ACTIVE" | "WAITING_REVIEW" | "DONE";
        /** StageUpdateRequest */
        StageUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Owner Id */
            owner_id?: string | null;
            /** Weight */
            weight?: number | null;
            status?: components["schemas"]["StageStatus"] | null;
        };
        /** StatusHistoryRead */
        StatusHistoryRead: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** From Status */
            from_status: string;
            /** To Status */
            to_status: string;
            /** Actor Id */
            actor_id: string;
            /** Actor Name */
            actor_name: string;
            /** Action */
            action: string;
            /** Reason */
            reason: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SubmissionRead */
        SubmissionRead: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** Version */
            version: number;
            /** Submitted By */
            submitted_by: string;
            /** Submitter Name */
            submitter_name: string;
            /** Summary */
            summary: string;
            /** External Url */
            external_url: string | null;
            /** Asset Reference */
            asset_reference: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TaskActionRequest */
        TaskActionRequest: {
            /** Expected Version */
            expected_version: number;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** External Url */
            external_url?: string | null;
            /** Asset Reference */
            asset_reference?: string | null;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Contact Id */
            contact_id?: string | null;
            /** Item */
            item?: string | null;
            /** Expected At */
            expected_at?: string | null;
            /** Internal Followup User Id */
            internal_followup_user_id?: string | null;
            /** Recovery Action */
            recovery_action?: string | null;
            /** Agent Run Id */
            agent_run_id?: string | null;
        };
        /** TaskActionResponse */
        TaskActionResponse: {
            task: components["schemas"]["TaskRead"];
            /**
             * Idempotent Replay
             * @default false
             */
            idempotent_replay: boolean;
        };
        /** TaskCreateRequest */
        TaskCreateRequest: {
            /** Project Id */
            project_id: string;
            /** Stage Id */
            stage_id?: string | null;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Deliverable */
            deliverable: string;
            /** Acceptance */
            acceptance: string;
            /** Owner Id */
            owner_id: string;
            /** Reviewer Id */
            reviewer_id: string;
            /** @default HUMAN */
            execution_mode: components["schemas"]["ExecutionMode"];
            /**
             * Priority
             * @default MEDIUM
             */
            priority: string;
            /** Due At */
            due_at?: string | null;
        };
        /** TaskRead */
        TaskRead: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Project Name */
            project_name: string;
            /** Stage Id */
            stage_id: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Deliverable */
            deliverable: string;
            /** Acceptance */
            acceptance: string;
            /** Owner Id */
            owner_id: string;
            /** Owner Name */
            owner_name: string;
            /** Reviewer Id */
            reviewer_id: string;
            /** Reviewer Name */
            reviewer_name: string;
            status: components["schemas"]["TaskStatus"];
            execution_mode: components["schemas"]["ExecutionMode"];
            /** Priority */
            priority: string;
            /** Progress */
            progress: number;
            /** Due At */
            due_at: string | null;
            /** Source */
            source: string;
            /** Version */
            version: number;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "PENDING_OWNER_CONFIRMATION" | "TODO" | "IN_PROGRESS" | "WAITING_EXTERNAL" | "BLOCKED" | "WAITING_HUMAN_CONFIRMATION" | "WAITING_REVIEW" | "DONE" | "CANCELED";
        /** TeamMemberRead */
        TeamMemberRead: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["TeamRole"];
            /** Is Active */
            is_active: boolean;
        };
        /** TeamRead */
        TeamRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            role: components["schemas"]["TeamRole"] | null;
            /** Members */
            members: components["schemas"]["TeamMemberRead"][];
            /** Project Names */
            project_names: string[];
        };
        /**
         * TeamRole
         * @enum {string}
         */
        TeamRole: "CEO" | "MEMBER";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserRead"];
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["TeamRole"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeComDocumentCreateRequest */
        WeComDocumentCreateRequest: {
            /** Doc Name */
            doc_name: string;
            /**
             * Doc Type
             * @default 10
             * @enum {integer}
             */
            doc_type: 3 | 4 | 10;
            /** Admin Users */
            admin_users?: string[];
            /** Spaceid */
            spaceid?: string | null;
            /** Fatherid */
            fatherid?: string | null;
        };
        /** WeComDocumentRead */
        WeComDocumentRead: {
            /** Docid */
            docid: string;
            /** Doc Url */
            doc_url?: string | null;
            /** Doc Name */
            doc_name?: string | null;
            /** Doc Type */
            doc_type?: number | null;
        };
        /** WeComStatusRead */
        WeComStatusRead: {
            /**
             * Provider
             * @default WECOM
             * @constant
             */
            provider: "WECOM";
            /** Configured */
            configured: boolean;
            /** Connected */
            connected: boolean;
            /** Detail */
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    change_password_api_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_api_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"][];
                };
            };
        };
    };
    team_invitations_api_teams__team_id__invitations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationAdminRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_team_member_api_teams__team_id__invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationCreatedRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invitation_api_teams__team_id__invitations__invitation_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationAdminRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_invitation_api_invitations__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationPublicRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_invitation_api_invitations__token__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationAcceptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_existing_account_invitation_api_invitations__token__accept_existing_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationAdminRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wecom_status_api_integrations_wecom_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeComStatusRead"];
                };
            };
        };
    };
    create_wecom_document_api_integrations_wecom_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeComDocumentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeComDocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wecom_document_api_integrations_wecom_documents__docid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeComDocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_members_api_projects__project_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decompose_project_api_projects__project_id__decompositions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectDecompositionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_task_overview_api_projects__project_id__task_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectTaskOverviewRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_conversations_api_projects__project_id__conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectConversationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_conversation_api_projects__project_id__conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectConversationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectConversationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_chat_messages_api_project_conversations__conversation_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectChatMessageRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_project_chat_message_api_project_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectChatSendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectChatSendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stage_api_projects__project_id__stages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stage_api_stages__stage_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stage_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_action_api_tasks__task_id__actions__action__post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                task_id: string;
                action: "ACCEPT" | "START" | "SUBMIT" | "APPROVE" | "RETURN" | "WAIT_EXTERNAL" | "RESUME_EXTERNAL" | "CONFIRM_AI" | "REVISE_AI" | "CANCEL";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_submissions_api_tasks__task_id__submissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_history_api_tasks__task_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusHistoryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    external_contacts_api_external_contacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalContactRead"][];
                };
            };
        };
    };
    task_external_dependency_api_tasks__task_id__external_dependency_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalDependencyRead"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    external_reminders_api_external_reminders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalReminderRead"][];
                };
            };
        };
    };
    create_candidate_extraction_api_candidate_extractions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateExtractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidates_api_candidates_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_candidate_api_candidates__candidate_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_candidate_route_api_candidates__candidate_id__confirm_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateConfirmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ignore_candidate_api_candidates__candidate_id__ignore_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_agent_runs_api_tasks__task_id__agent_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_run_api_tasks__task_id__agent_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AgentRunStartRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_runs_api_agent_runs_get: {
        parameters: {
            query?: {
                status?: string | null;
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contributions_api_contributions_get: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
