/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Task Action */
        post: operations["task_action_api_tasks__task_id__actions__action__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Submissions */
        get: operations["task_submissions_api_tasks__task_id__submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task History */
        get: operations["task_history_api_tasks__task_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ExecutionMode
         * @enum {string}
         */
        ExecutionMode: "HUMAN" | "AI" | "HYBRID";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** ProjectRead */
        ProjectRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Client */
            client: string;
            /** Objective */
            objective: string;
            /** Owner Id */
            owner_id: string;
            /** Owner Name */
            owner_name: string;
            /** Next Milestone */
            next_milestone: string;
            /** Due At */
            due_at: string | null;
            /** Progress */
            progress: number;
            /**
             * Health
             * @enum {string}
             */
            health: "正常" | "有风险" | "需关注";
            /** Current Stage */
            current_stage: string;
            /** Stages */
            stages: components["schemas"]["StageRead"][];
        };
        /** StageRead */
        StageRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: number;
            status: components["schemas"]["StageStatus"];
            /** Progress */
            progress: number;
        };
        /**
         * StageStatus
         * @enum {string}
         */
        StageStatus: "PLANNED" | "ACTIVE" | "WAITING_REVIEW" | "DONE";
        /** StatusHistoryRead */
        StatusHistoryRead: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** From Status */
            from_status: string;
            /** To Status */
            to_status: string;
            /** Actor Id */
            actor_id: string;
            /** Actor Name */
            actor_name: string;
            /** Action */
            action: string;
            /** Reason */
            reason: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SubmissionRead */
        SubmissionRead: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** Version */
            version: number;
            /** Submitted By */
            submitted_by: string;
            /** Submitter Name */
            submitter_name: string;
            /** Summary */
            summary: string;
            /** External Url */
            external_url: string | null;
            /** Asset Reference */
            asset_reference: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TaskActionRequest */
        TaskActionRequest: {
            /** Expected Version */
            expected_version: number;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** External Url */
            external_url?: string | null;
            /** Asset Reference */
            asset_reference?: string | null;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** TaskActionResponse */
        TaskActionResponse: {
            task: components["schemas"]["TaskRead"];
            /**
             * Idempotent Replay
             * @default false
             */
            idempotent_replay: boolean;
        };
        /** TaskRead */
        TaskRead: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Project Name */
            project_name: string;
            /** Stage Id */
            stage_id: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Deliverable */
            deliverable: string;
            /** Acceptance */
            acceptance: string;
            /** Owner Id */
            owner_id: string;
            /** Owner Name */
            owner_name: string;
            /** Reviewer Id */
            reviewer_id: string;
            /** Reviewer Name */
            reviewer_name: string;
            status: components["schemas"]["TaskStatus"];
            execution_mode: components["schemas"]["ExecutionMode"];
            /** Priority */
            priority: string;
            /** Progress */
            progress: number;
            /** Due At */
            due_at: string | null;
            /** Source */
            source: string;
            /** Version */
            version: number;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "PENDING_OWNER_CONFIRMATION" | "TODO" | "IN_PROGRESS" | "WAITING_EXTERNAL" | "BLOCKED" | "WAITING_HUMAN_CONFIRMATION" | "WAITING_REVIEW" | "DONE" | "CANCELED";
        /**
         * TeamRole
         * @enum {string}
         */
        TeamRole: "CEO" | "MEMBER";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserRead"];
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["TeamRole"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"][];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_action_api_tasks__task_id__actions__action__post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                task_id: string;
                action: "ACCEPT" | "START" | "SUBMIT" | "APPROVE" | "RETURN" | "CANCEL";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_submissions_api_tasks__task_id__submissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_history_api_tasks__task_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusHistoryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
