/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Task Action */
        post: operations["task_action_api_tasks__task_id__actions__action__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Submissions */
        get: operations["task_submissions_api_tasks__task_id__submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task History */
        get: operations["task_history_api_tasks__task_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/external-contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** External Contacts */
        get: operations["external_contacts_api_external_contacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/external-dependency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task External Dependency */
        get: operations["task_external_dependency_api_tasks__task_id__external_dependency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/external-reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** External Reminders */
        get: operations["external_reminders_api_external_reminders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate-extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Candidate Extraction */
        post: operations["create_candidate_extraction_api_candidate_extractions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Candidates */
        get: operations["list_candidates_api_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Candidate */
        patch: operations["update_candidate_api_candidates__candidate_id__patch"];
        trace?: never;
    };
    "/api/candidates/{candidate_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Candidate Route */
        post: operations["confirm_candidate_route_api_candidates__candidate_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/ignore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ignore Candidate */
        post: operations["ignore_candidate_api_candidates__candidate_id__ignore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/agent-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Agent Runs */
        get: operations["task_agent_runs_api_tasks__task_id__agent_runs_get"];
        put?: never;
        /** Create Agent Run */
        post: operations["create_agent_run_api_tasks__task_id__agent_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentRunRead */
        AgentRunRead: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** Status */
            status: string;
            /** Execution Mode */
            execution_mode: string | null;
            /** Degraded */
            degraded: boolean;
            /** Fallback Reason */
            fallback_reason: string | null;
            /** Prompt Version */
            prompt_version: string;
            /** Attempt Count */
            attempt_count: number;
            /** Max Attempts */
            max_attempts: number;
            /** Output Text */
            output_text: string;
            /** Error Message */
            error_message: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AgentRunStartResponse */
        AgentRunStartResponse: {
            run: components["schemas"]["AgentRunRead"];
            /** Idempotent Replay */
            idempotent_replay: boolean;
        };
        /** CandidateConfirmRequest */
        CandidateConfirmRequest: {
            /** Expected Version */
            expected_version: number;
        };
        /** CandidateConfirmResponse */
        CandidateConfirmResponse: {
            candidate: components["schemas"]["CandidateRead"];
            task: components["schemas"]["TaskRead"];
            /**
             * Idempotent Replay
             * @default false
             */
            idempotent_replay: boolean;
        };
        /** CandidateExtractionRequest */
        CandidateExtractionRequest: {
            /** Project Id */
            project_id: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "MEETING" | "CHAT" | "DOCUMENT" | "AI_CHAT";
            /** Title */
            title: string;
            /** Content */
            content: string;
        };
        /** CandidateExtractionResponse */
        CandidateExtractionResponse: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Candidates */
            candidates: components["schemas"]["CandidateRead"][];
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "LIVE" | "MOCK" | "FALLBACK";
            /** Degraded */
            degraded: boolean;
            /** Fallback Reason */
            fallback_reason: string | null;
            /** Cached */
            cached: boolean;
            /** Call Id */
            call_id: string;
        };
        /** CandidateRead */
        CandidateRead: {
            /** Id */
            id: string;
            /** Source Snapshot Id */
            source_snapshot_id: string;
            /** Project Id */
            project_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Deliverable */
            deliverable: string;
            /** Owner Id */
            owner_id: string | null;
            /** Reviewer Id */
            reviewer_id: string | null;
            /** Due At */
            due_at: string | null;
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence: string;
            /** Status */
            status: string;
            /** Created Task Id */
            created_task_id: string | null;
            /** Version */
            version: number;
        };
        /** CandidateUpdateRequest */
        CandidateUpdateRequest: {
            /** Expected Version */
            expected_version: number;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Deliverable */
            deliverable?: string | null;
            /** Owner Id */
            owner_id?: string | null;
            /** Reviewer Id */
            reviewer_id?: string | null;
            /** Due At */
            due_at?: string | null;
        };
        /**
         * ExecutionMode
         * @enum {string}
         */
        ExecutionMode: "HUMAN" | "AI" | "HYBRID";
        /** ExternalContactRead */
        ExternalContactRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Organization */
            organization: string;
            /** Channel */
            channel: string;
        };
        /** ExternalDependencyRead */
        ExternalDependencyRead: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** Contact Id */
            contact_id: string;
            /** Contact Name */
            contact_name: string;
            /** Item */
            item: string;
            /**
             * Expected At
             * Format: date-time
             */
            expected_at: string;
            /** Internal Followup User Id */
            internal_followup_user_id: string;
            /** Internal Followup User Name */
            internal_followup_user_name: string;
            /** Recovery Action */
            recovery_action: string;
            /** Last Followup At */
            last_followup_at: string | null;
            /** External Feedback Status */
            external_feedback_status: string;
            /** Actual Received At */
            actual_received_at: string | null;
            /** Reminder Sent */
            reminder_sent: boolean;
            /**
             * Reminder Level
             * @enum {string}
             */
            reminder_level: "NORMAL" | "UPCOMING" | "OVERDUE" | "RECEIVED";
        };
        /** ExternalReminderRead */
        ExternalReminderRead: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** Reminder Type */
            reminder_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** ProjectRead */
        ProjectRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Client */
            client: string;
            /** Objective */
            objective: string;
            /** Owner Id */
            owner_id: string;
            /** Owner Name */
            owner_name: string;
            /** Next Milestone */
            next_milestone: string;
            /** Due At */
            due_at: string | null;
            /** Progress */
            progress: number;
            /**
             * Health
             * @enum {string}
             */
            health: "正常" | "有风险" | "需关注";
            /** Current Stage */
            current_stage: string;
            /** Stages */
            stages: components["schemas"]["StageRead"][];
        };
        /** StageRead */
        StageRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: number;
            status: components["schemas"]["StageStatus"];
            /** Progress */
            progress: number;
        };
        /**
         * StageStatus
         * @enum {string}
         */
        StageStatus: "PLANNED" | "ACTIVE" | "WAITING_REVIEW" | "DONE";
        /** StatusHistoryRead */
        StatusHistoryRead: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** From Status */
            from_status: string;
            /** To Status */
            to_status: string;
            /** Actor Id */
            actor_id: string;
            /** Actor Name */
            actor_name: string;
            /** Action */
            action: string;
            /** Reason */
            reason: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SubmissionRead */
        SubmissionRead: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** Version */
            version: number;
            /** Submitted By */
            submitted_by: string;
            /** Submitter Name */
            submitter_name: string;
            /** Summary */
            summary: string;
            /** External Url */
            external_url: string | null;
            /** Asset Reference */
            asset_reference: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TaskActionRequest */
        TaskActionRequest: {
            /** Expected Version */
            expected_version: number;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** External Url */
            external_url?: string | null;
            /** Asset Reference */
            asset_reference?: string | null;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Contact Id */
            contact_id?: string | null;
            /** Item */
            item?: string | null;
            /** Expected At */
            expected_at?: string | null;
            /** Internal Followup User Id */
            internal_followup_user_id?: string | null;
            /** Recovery Action */
            recovery_action?: string | null;
            /** Agent Run Id */
            agent_run_id?: string | null;
        };
        /** TaskActionResponse */
        TaskActionResponse: {
            task: components["schemas"]["TaskRead"];
            /**
             * Idempotent Replay
             * @default false
             */
            idempotent_replay: boolean;
        };
        /** TaskRead */
        TaskRead: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Project Name */
            project_name: string;
            /** Stage Id */
            stage_id: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Deliverable */
            deliverable: string;
            /** Acceptance */
            acceptance: string;
            /** Owner Id */
            owner_id: string;
            /** Owner Name */
            owner_name: string;
            /** Reviewer Id */
            reviewer_id: string;
            /** Reviewer Name */
            reviewer_name: string;
            status: components["schemas"]["TaskStatus"];
            execution_mode: components["schemas"]["ExecutionMode"];
            /** Priority */
            priority: string;
            /** Progress */
            progress: number;
            /** Due At */
            due_at: string | null;
            /** Source */
            source: string;
            /** Version */
            version: number;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "PENDING_OWNER_CONFIRMATION" | "TODO" | "IN_PROGRESS" | "WAITING_EXTERNAL" | "BLOCKED" | "WAITING_HUMAN_CONFIRMATION" | "WAITING_REVIEW" | "DONE" | "CANCELED";
        /**
         * TeamRole
         * @enum {string}
         */
        TeamRole: "CEO" | "MEMBER";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserRead"];
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["TeamRole"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"][];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_action_api_tasks__task_id__actions__action__post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                task_id: string;
                action: "ACCEPT" | "START" | "SUBMIT" | "APPROVE" | "RETURN" | "WAIT_EXTERNAL" | "RESUME_EXTERNAL" | "CONFIRM_AI" | "REVISE_AI" | "CANCEL";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_submissions_api_tasks__task_id__submissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_history_api_tasks__task_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusHistoryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    external_contacts_api_external_contacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalContactRead"][];
                };
            };
        };
    };
    task_external_dependency_api_tasks__task_id__external_dependency_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalDependencyRead"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    external_reminders_api_external_reminders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalReminderRead"][];
                };
            };
        };
    };
    create_candidate_extraction_api_candidate_extractions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateExtractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidates_api_candidates_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_candidate_api_candidates__candidate_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_candidate_route_api_candidates__candidate_id__confirm_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateConfirmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ignore_candidate_api_candidates__candidate_id__ignore_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_agent_runs_api_tasks__task_id__agent_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_run_api_tasks__task_id__agent_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
