import type { AppState, Task } from "./types";
const d = (n: number) =>
  new Date(Date.now() + n * 86400000).toISOString().slice(0, 10);
const task = (
  id: string,
  title: string,
  projectId: string,
  ownerId: string,
  status: Task["status"],
  mode: Task["mode"],
  due: number,
  extra: Partial<Task> = {},
): Task => ({
  id,
  title,
  projectId,
  ownerId,
  status,
  mode,
  dueAt: d(due),
  priority: "中",
  background: "来自项目协作上下文，需要形成明确、可跟踪的交付。",
  objective: "按计划推进并提交可验收结果。",
  deliverable: "可审阅的阶段成果与执行说明",
  acceptance: "负责人确认内容完整、结果可用。",
  points: 10,
  source: "手动创建",
  ...extra,
});
export const initialState: AppState = {
  users: [
    {
      id: "u1",
      name: "泉哥",
      role: "CEO / 负责人",
      initials: "泉",
      color: "#245c45",
    },
    {
      id: "u2",
      name: "产品经理A",
      role: "AI 产品经理",
      initials: "A",
      color: "#6d5bd0",
    },
    {
      id: "u3",
      name: "产品经理B",
      role: "AI 产品经理",
      initials: "B",
      color: "#b26b2c",
    },
    {
      id: "u4",
      name: "产品运营",
      role: "产品运营",
      initials: "运",
      color: "#35718c",
    },
    {
      id: "u5",
      name: "全栈工程师",
      role: "全栈工程师",
      initials: "全",
      color: "#42556d",
    },
  ],
  projects: [
    {
      id: "p1",
      name: "MedKungFu",
      description: "AI 医疗能力与产品交付项目",
      stage: "Beta 验证",
      ownerId: "u2",
      progress: 68,
      risk: "中",
      color: "#2563eb",
    },
    {
      id: "p2",
      name: "FANNAL",
      description: "智能销售与客户运营平台",
      stage: "需求验证",
      ownerId: "u3",
      progress: 42,
      risk: "高",
      color: "#6366f1",
    },
    {
      id: "p3",
      name: "全意品牌",
      description: "品牌内容与官网升级",
      stage: "内容生产",
      ownerId: "u4",
      progress: 76,
      risk: "低",
      color: "#0891b2",
    },
  ],
  contacts: [
    { id: "c1", name: "林医生", company: "康宁医疗", role: "试点负责人" },
    { id: "c2", name: "陈总", company: "远川科技", role: "客户负责人" },
    { id: "c3", name: "Mia", company: "North Studio", role: "设计顾问" },
    { id: "c4", name: "周老师", company: "行业协会", role: "内容顾问" },
  ],
  tasks: [
    task(
      "t1",
      "整理 MedKungFu Beta 反馈",
      "p1",
      "u2",
      "IN_PROGRESS",
      "HUMAN",
      1,
      { priority: "高", points: 20 },
    ),
    task(
      "t2",
      "生成问诊工作流测试用例",
      "p1",
      "u5",
      "IN_PROGRESS",
      "HYBRID",
      2,
      { agentRunId: "r1" },
    ),
    task("t3", "FANNAL 客户画像初版", "p2", "u3", "TODO", "HUMAN", 3),
    task("t4", "品牌官网首页文案", "p3", "u4", "WAITING_REVIEW", "HUMAN", 0),
    task("t5", "竞品能力矩阵更新", "p1", "u2", "TODO", "AI", 4, {
      agentRunId: "r2",
    }),
    task("t6", "修复任务状态同步问题", "p2", "u5", "BLOCKED", "HUMAN", 1, {
      priority: "紧急",
      internalBlock: true,
    }),
    task("t7", "准备周五项目复盘", "p1", "u2", "TODO", "HYBRID", 2),
    task("t8", "整理品牌视觉素材清单", "p3", "u4", "TODO", "HUMAN", 5),
    task(
      "t9",
      "确认 FANNAL 报价范围",
      "p2",
      "u1",
      "WAITING_HUMAN_CONFIRMATION",
      "AI",
      1,
    ),
    task("t10", "补充医疗知识库来源说明", "p1", "u3", "TODO", "HUMAN", 6),
    task(
      "t11",
      "等待试点医院反馈",
      "p1",
      "u4",
      "WAITING_EXTERNAL",
      "HUMAN",
      1,
      {
        external: {
          contactId: "c1",
          item: "确认 Beta 试用反馈与下一轮排期",
          followupId: "u4",
          expectedAt: d(1),
          lastUpdate: d(-2),
        },
      },
    ),
    task(
      "t12",
      "等待客户确认合同条款",
      "p2",
      "u1",
      "WAITING_EXTERNAL",
      "HUMAN",
      -1,
      {
        priority: "高",
        external: {
          contactId: "c2",
          item: "确认数据与服务范围条款",
          followupId: "u1",
          expectedAt: d(-1),
          lastUpdate: d(-3),
        },
      },
    ),
    task(
      "t13",
      "等待品牌插画源文件",
      "p3",
      "u4",
      "WAITING_EXTERNAL",
      "HUMAN",
      9,
      {
        external: {
          contactId: "c3",
          item: "交付首页插画可编辑源文件",
          followupId: "u4",
          noExpectedTime: true,
          lastUpdate: d(-1),
        },
      },
    ),
  ],
  candidates: [
    {
      id: "q1",
      title: "补充 MedKungFu 数据安全说明",
      sourceType: "聊天",
      sourceText:
        "泉哥：医院那边问到数据怎么存，A 你整理一版安全说明，下周一前给我。",
      initiator: "泉哥",
      detectedAt: "今天 09:42",
      confidence: 94,
      missing: [],
      projectId: "p1",
      ownerId: "u2",
      mode: "HYBRID",
      dueAt: d(3),
      background: "试点医院关注数据存储与隐私保护方式。",
      objective: "形成对外可用的数据安全说明。",
      deliverable: "数据安全说明文档 V1",
      acceptance: "覆盖存储、传输、访问权限及隐私边界。",
      priority: "高",
      points: 20,
      state: "ACTIVE",
    },
    {
      id: "q2",
      title: "安排 FANNAL 需求评审",
      sourceType: "会议",
      sourceText: "会议决议：产品经理B负责组织需求评审，工程师参加，本周完成。",
      initiator: "FANNAL 周会",
      detectedAt: "昨天 17:20",
      confidence: 91,
      missing: [],
      projectId: "p2",
      ownerId: "u3",
      mode: "HUMAN",
      dueAt: d(2),
      background: "需求边界需要与技术团队统一。",
      objective: "完成需求评审并记录结论。",
      deliverable: "评审纪要与行动项",
      acceptance: "关键范围、风险和负责人均有结论。",
      priority: "高",
      points: 10,
      state: "ACTIVE",
      isMeeting: true,
    },
    {
      id: "q3",
      title: "优化品牌介绍页移动文案",
      sourceType: "Codex",
      sourceText:
        "Codex 运行记录：检测到品牌介绍页存在 3 处表达不一致，建议统一。",
      initiator: "Codex",
      detectedAt: "昨天 15:06",
      confidence: 82,
      missing: ["截止时间"],
      projectId: "p3",
      ownerId: "u4",
      mode: "AI",
      dueAt: d(5),
      background: "品牌页面文案表达不统一。",
      objective: "统一核心品牌表达。",
      deliverable: "更新后的页面文案",
      acceptance: "三处表达与品牌语调一致。",
      priority: "中",
      points: 10,
      state: "ACTIVE",
    },
    {
      id: "q4",
      title: "跟进客户演示环境账号",
      sourceType: "聊天",
      sourceText: "产品运营：我来找客户确认演示账号什么时候能开通。",
      initiator: "产品运营",
      detectedAt: "周一 11:18",
      confidence: 76,
      missing: ["验收标准"],
      projectId: "p2",
      ownerId: "u4",
      mode: "HUMAN",
      dueAt: d(4),
      background: "演示准备依赖客户开通环境账号。",
      objective: "确认账号开通时间和访问方式。",
      deliverable: "可用账号或明确时间",
      acceptance: "",
      priority: "中",
      points: 5,
      state: "ACTIVE",
    },
  ],
  agents: [
    { id: "a1", name: "Codex Engineer", type: "代码执行", status: "忙碌" },
    { id: "a2", name: "Research Agent", type: "研究分析", status: "在线" },
  ],
  runs: [
    {
      id: "r1",
      taskId: "t2",
      agentId: "a1",
      status: "RUNNING",
      progress: 62,
      step: "生成边界条件用例",
      elapsed: "18 分 24 秒",
      logs: [
        "读取 PRD 与现有测试结构",
        "已生成基础流程用例 12 条",
        "正在补充异常路径",
      ],
      files: ["test-cases-draft.md"],
      toolCalls: ["读取项目文档", "分析任务依赖"],
    },
    {
      id: "r2",
      taskId: "t5",
      agentId: "a2",
      status: "QUEUED",
      progress: 8,
      step: "等待执行资源",
      elapsed: "2 分 10 秒",
      logs: ["任务已进入队列"],
      files: [],
      toolCalls: [],
    },
  ],
  helps: [
    {
      id: "h1",
      question: "如何定义问诊建议的安全边界？",
      taskId: "t2",
      urgency: "紧急",
      status: "AI_ANSWERED",
      attempted: "查阅现有 PRD 和历史评审记录。",
      aiAnswer:
        "建议将输出限定为健康信息整理和就医建议，不做诊断或处方，并保留人工复核。",
      recommended: ["u2", "u3"],
    },
    {
      id: "h2",
      question: "客户画像字段是否需要加入决策链角色？",
      taskId: "t3",
      urgency: "普通",
      status: "NEEDS_EXPERT",
      attempted: "对比了两份访谈记录，仍有差异。",
      aiAnswer: "历史资料不足以形成确定结论，建议由产品负责人确认。",
      recommended: ["u1", "u3"],
    },
  ],
  contributions: [
    {
      id: "n1",
      userId: "u2",
      type: "完成任务",
      description: "完成问诊流程需求拆解",
      points: 20,
      date: d(-2),
    },
    {
      id: "n2",
      userId: "u4",
      type: "解决求助",
      description: "补充客户运营跟进规范",
      points: 5,
      date: d(-3),
    },
    {
      id: "n3",
      userId: "u5",
      type: "知识沉淀",
      description: "整理 Codex 执行注意事项",
      points: 3,
      date: d(-4),
    },
  ],
};
