"""task workflow audit and submissions

Revision ID: 28cc6b1cf56f
Revises: d5ee36a95659
Create Date: 2026-08-19 19:00:16.022503
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '28cc6b1cf56f'
down_revision: Union[str, None] = 'd5ee36a95659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditevent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditevent_actor_id'), 'auditevent', ['actor_id'], unique=False)
    op.create_index(op.f('ix_auditevent_resource_id'), 'auditevent', ['resource_id'], unique=False)
    op.create_table('idempotencyrecord',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('taskstatushistory',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskstatushistory_task_id'), 'taskstatushistory', ['task_id'], unique=False)
    op.create_table('tasksubmission',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'version', name='uq_task_submission_version')
    )
    op.create_index(op.f('ix_tasksubmission_task_id'), 'tasksubmission', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasksubmission_task_id'), table_name='tasksubmission')
    op.drop_table('tasksubmission')
    op.drop_index(op.f('ix_taskstatushistory_task_id'), table_name='taskstatushistory')
    op.drop_table('taskstatushistory')
    op.drop_table('idempotencyrecord')
    op.drop_index(op.f('ix_auditevent_resource_id'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_actor_id'), table_name='auditevent')
    op.drop_table('auditevent')
    # ### end Alembic commands ###
